# Generated by Django 5.2.3 on 2025-07-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('absence_content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Auditing'), (2, 'Approval'), (3, 'Reject')], default=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('responder_content', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_absents', related_query_name='my_absents', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_absents', related_query_name='sub_absents', to=settings.AUTH_USER_MODEL)),
                ('absent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', related_query_name='absents', to='attendance.absenttype')),
            ],
        ),
    ]
